/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTableIndexRouteImport } from './routes/_app/table/index'
import { Route as AppGeolocationIndexRouteImport } from './routes/_app/geolocation/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTableIndexRoute = AppTableIndexRouteImport.update({
  id: '/_app/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGeolocationIndexRoute = AppGeolocationIndexRouteImport.update({
  id: '/_app/geolocation/',
  path: '/geolocation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/_app/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/geolocation': typeof AppGeolocationIndexRoute
  '/table': typeof AppTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/geolocation': typeof AppGeolocationIndexRoute
  '/table': typeof AppTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/': typeof AppIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/geolocation/': typeof AppGeolocationIndexRoute
  '/_app/table/': typeof AppTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/geolocation' | '/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/geolocation' | '/table'
  id:
    | '__root__'
    | '/_app/'
    | '/_app/dashboard/'
    | '/_app/geolocation/'
    | '/_app/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppGeolocationIndexRoute: typeof AppGeolocationIndexRoute
  AppTableIndexRoute: typeof AppTableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/table/': {
      id: '/_app/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AppTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/geolocation/': {
      id: '/_app/geolocation/'
      path: '/geolocation'
      fullPath: '/geolocation'
      preLoaderRoute: typeof AppGeolocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppGeolocationIndexRoute: AppGeolocationIndexRoute,
  AppTableIndexRoute: AppTableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
